spring:
  application:
    name: order-service

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order_service
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
