spring:
  application:
    name: product-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Ecommerce-Microservice/protocol/openid-connect/certs


  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/product_service
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8001